<style>
    #hiddenBaseField{display: none;}
    #container_tables, #hiddenElements{display: none;}
    
    #progessDialog{
        position: absolute;
        top: 100px;
        left: 200px;
        width: 600px;
        display: none;
    }
    #progessDialog div.panel-heading span{
        float: right;
        cursor: pointer;
        display: none;
    }

    .progress-bar span{
        font-weight: bold;
        text-shadow: #333 2px 2px 1px;
    }
    
    #progessDialog #show_results{float: right;}
</style>

<script>
    $(document).ready(function() {      
        
        $(window).bind("resize", function() {
            elementResize();
        });
        function elementResize() {
            $("#progessDialog").css("left", ( ($("#page-wrapper").width() / 2 ) - $("#progessDialog").width() / 2 ) );
            $("#progessDialog").css("top", ( ($("#page-wrapper").height() / 4 ) - $("#progessDialog").height() / 2 ) );
        }
        elementResize();
        
        function getPreparedArray()
        {
            var tableArray =  new Array();
            <?php
            $i = 0;
            foreach ($this->tablesCollection as $table) {
                $searchableFields = $table->getValueByKey("searchableFields");
                
                echo "" . PHP_EOL;
                echo "tableArray['" . $table->getValueByKey("name") . "'] = new Object();" . PHP_EOL;
                echo "tableArray['" . $table->getValueByKey("name") . "']['searchableFields'] = new Object();" . PHP_EOL;
                $k = 0;
                foreach($searchableFields as $searchField){
                    echo "tableArray['" . $table->getValueByKey("name") . "']['searchableFields']['". $k++ ."'] = '" . $searchField . "';" . PHP_EOL;
                }
                echo "" . PHP_EOL;
                $i++;
            }
            ?>
            return tableArray;
        }
        
        function getPreparedPortalArray()
        {
            var portalArray =  new Object();
            <?php

            if ($this->entity){
                echo "" . PHP_EOL;
                if($this->entity->getValueByKey("scan_exclude") < 1 ){
                    echo "portalArray['" . $this->entity->getValueByKey("name") . "'] = " . $this->entity->getId() . ";" . PHP_EOL;
                }
                echo "" . PHP_EOL;
            } else if($this->collection) {

                echo "" . PHP_EOL;
                foreach($this->collection as $portal){
                    if($portal->getValueByKey("scan_exclude") < 1 ){
                        echo "portalArray['" . $portal->getValueByKey("name") . "'] = " . $portal->getId() . ";" . PHP_EOL;
                    }
                }
                echo "" . PHP_EOL;
            }

            ?>
            return portalArray;
        }
        
        $('#tablenames').change(function() {
            $("div#searchFields div#containerSearchFields").html("");
            
            var tablename = $(this).find(":selected").text();
            var tableArray = getPreparedArray();
                        
            for (var index in tableArray[tablename]['searchableFields']) {
                if (tableArray[tablename]['searchableFields'].hasOwnProperty(index)) {
                    
                    var searchField = tableArray[tablename]['searchableFields'][index];
                    $("div#hiddenBaseField > div label").attr("for", "searchQuery_" + searchField);
                    $("div#hiddenBaseField > div label").html(searchField);
                    $("div#hiddenBaseField > div > div > input").attr("id", "searchQuery_" + searchField);
                    $("div#hiddenBaseField > div > div > input").attr("name", searchField);
                    $("div#hiddenBaseField > div > div > input").val("");
                   
                    $("div#hiddenBaseField > div").clone().appendTo("div#searchFields div#containerSearchFields");
                }
            }
        });
        
        $("#submit_btn").click(function(){
            var startSearch = false;
            data = new FormData();
            data.append("tablename", $("#tablenames").find(":selected").text());

            $("#containerSearchFields input").each(function() {
                if($(this).val() !== ""){
                    data.append($(this).attr("name"), $(this).val());
                    startSearch = true;
                }
            });

            if(startSearch === true) {
                $("#container_tables").hide();
                $("#progessDialog div.progress-bar").removeClass("progress-bar-success");
                $("#progessDialog").removeClass("panel-success");
                $("#progessDialog").addClass("panel-default");
                $("#progessDialog div.panel-heading span").hide();
                $("#progessDialog #show_results_container").hide();
                $("#container_tables").html("");
                $("#progessDialog").show();
                
                var portalArray = getPreparedPortalArray();
                var portalsCount = <?php
                    if($this->entity) {
                        echo 1;

                    } else if($this->collection) {
                        $i = 0;
                        foreach($this->collection as $portal){
                            if($portal->getValueByKey("scan_exclude") < 1 ){
                                $i++;

                            }
                        } echo $i;
                    }
                            ?>;
                var i = 0;
                var percent = 0;
                $.each(portalArray, function(portal, portal_id) {
                    $.ajax({
                         url: "<?php echo \lw_page::getInstance()->getUrl(array("portalsPlugin" =>"LwPortalsTableSearch", "cmd" => "search", "ajax" => 1)); ?>&id=" + portal_id,
                         data: data,
                         type: "POST",
                         dataType: "json",
                         processData: false,
                         contentType: false
                         }).done(function(response){
                             i++;
                             percent = ((i/portalsCount) * 100).toFixed(2);
                             $("#progessDialog div.progress-bar").css("width", percent + "%");
                             $("#progessDialog div.progress-bar span").html("<nobr>" + portal +" ( " + percent +"% )</nobr>");
                             if( i === portalsCount) {
                                $("#progessDialog div.progress-bar").addClass("progress-bar-success");
                                $("#progessDialog").removeClass("panel-default");
                                $("#progessDialog").addClass("panel-success");
                                $("#progessDialog div.panel-heading span").show();
                                $("#progessDialog #show_results_container").show();
                             }
                             buildTable(response);
                     });
                });
            }
       });
       
       function buildTable(jsonResponse)
       {
           var portalArray = getPreparedPortalArray();
           $.each(jsonResponse, function(portal, results) {
               $("#hiddenElements div.portalTableContainer").attr("id","container_" + portalArray[portal]).clone().appendTo($("#container_tables"));
               $("#hiddenElements div.headline h3").html(portal).clone().appendTo($("#container_tables div#container_" + portalArray[portal]));
               $("#hiddenElements div.table_frame table").clone().appendTo($("#container_tables div#container_" + portalArray[portal]));
               $.each(results, function(fields, searchResult) {
                   if(fields === "tablename") {
                       var tablename = searchResult;
                       $("#hiddenElements div.table_row tr td.search_tablename").html(tablename);
                   } else {
                       var searchQuery = searchResult.searchQuery;
                       $("#hiddenElements div.table_row tr td.search_string").html(searchQuery);                       
                       $.each(searchResult, function(nr, r) {
                           if(nr !== "searchQuery") {
                               $.each(r, function(k, v) {
                                   if(k !== "id" && k !== "name") {
                                       $("#hiddenElements div.table_row tr td.search_field").html(k);
                                       $("#hiddenElements div.table_row tr td.search_ext_field").html(v);
                                   } else {
                                       $("#hiddenElements div.table_row tr td.search_field").html("name");
                                       $("#hiddenElements div.table_row tr td.search_ext_field").html("&nbsp;");
                                   }
                               });
                               $("#hiddenElements div.table_row tr td.search_id").html(r.id);
                               $("#hiddenElements div.table_row tr td.search_name").html(r.name);
                               $("#hiddenElements div.table_row tr").clone().appendTo($("#container_tables div#container_" + portalArray[portal] + " > table > tbody"));
                           }
                       });
                   }
               });
            });
       }
        
       $("#progessDialog div.panel-heading span").click(function(){
          $("#container_tables").show();
          $("#progessDialog").hide();
       });
       $("#progessDialog #show_results").click(function(){
          $("#container_tables").show();
          $("#progessDialog").hide();
       });
    
        <?php if($this->post): ?>
            <?php $post = $this->post; unset($post["tablename"]); ?>
            <?php foreach($post as $field => $searchQuery): ?>
                $("div#hiddenBaseField > div label").attr("for", "searchQuery_<?php echo $field ?>");
                $("div#hiddenBaseField > div label").html("<?php echo $field ?>");
                $("div#hiddenBaseField > div > div > input").attr("id", "searchQuery_<?php echo $field ?>");
                $("div#hiddenBaseField > div > div > input").attr("name", "<?php echo $field ?>");
                $("div#hiddenBaseField > div > div > input").val("<?php echo $searchQuery ?>");

                $("div#hiddenBaseField > div").clone().appendTo("div#searchFields div#containerSearchFields");
            <?php endforeach; ?>
        <?php endif; ?>
    });
</script>

<?php if($this->entity): ?>
    <h1>Tabellensuche - <?php echo $this->entity->getValueByKey("name"); ?></h1>
<?php else: ?>
    <h1>Tabellensuche - Alle Portale</h1>
<?php endif; ?>
<hr>    

<?php if($this->entity): ?>
    <?php if(isset($this->pageIndexes["portals"])) { $indexPortals = $this->pageIndexes["portals"]; } else { $indexPortals = 0; } ?>
    <a href="<?php echo \lw_page::getInstance($indexPortals)->getUrl(array("portalsPlugin" =>"LwPortalsList", "cmd" => "showDetail", "id" => $this->entity->getId())); ?>" title="zur&uuml;ck"><span class="glyphicon glyphicon-arrow-left"></span></a>
<?php endif; ?>    

<form id="md5check_form" class="form-horizontal" role="form" action="<?php echo $this->actionUrl; ?>" method="POST">
    <div class="form-group" class="col-sm-4">
        <label for="tablenames" class="col-sm-2 control-label">Tabelle</label>
        <div class="col-sm-4">
            <select id="tablenames" name="tablename" class="form-control" size="15">
                <?php foreach ($this->tablesCollection as $table): ?>
                    <option value="<?php echo $table->getValueByKey("name"); ?>" <?php if($this->post["tablename"] == $table->getValueByKey("name")): ?>selected="selected"<?php endif; ?>><?php echo $table->getValueByKey("name"); ?></option>
                <?php endforeach; ?>
            </select>
        </div><br>
        
        <div id="searchFields" class="col-sm-6">
            <h5>Verf&uuml;gbare Suchfelder</h5>
            <div id="containerSearchFields"></div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input type="button" id="submit_btn" class="btn btn-default" value="suchen">
        </div>
    </div>
</form>

<div id="hiddenBaseField">
    <div class="form-group">
        <label for="searchQuery" class="col-sm-3 control-label">Name</label>
        <div class="col-sm-7">
            <input id="searchQuery" class="form-control" type="text" name="searchQuery" value=""/>
        </div>       
    </div>
</div>

<div id="container_tables"></div>

<?php if($this->results): ?>    
    <?php foreach($this->results as $portal => $results): ?>
        <?php 
        $extendedFields = array();
        $tablename = $results["tablename"];
        unset($results["tablename"]);

        foreach ($results as $field => $searchResults) {
            $searchQuery = $searchResults["searchQuery"];
            unset($searchResults["searchQuery"]);
            foreach($searchResults as $sr){
                foreach($sr as $key => $value){
                    if($key != "id" && $key != "name"){
                        $extendedFields[$key] = true;
                    }
                }
            } 
        } 
        ?>
        <h3><?php echo $portal; ?></h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Tabelle</th>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Suchstring</th>
                    <th>Suchfeld</th>
                    <?php foreach($extendedFields as $name => $isSet): ?>
                        <th style="font-style: italic;"><?php echo $name; ?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($results as $field => $searchResults): ?>
                    <?php $searchQuery = $searchResults["searchQuery"];unset($searchResults["searchQuery"]);?>
                    <?php foreach($searchResults as $sr): ?>
                        <tr>
                            <td><?php echo $tablename ?></td>
                            <td><?php echo $sr["id"]; ?></td>
                            <td><?php echo $sr["name"] ?></td>
                            <td><?php echo $searchQuery ?></td>
                            <td><?php echo $field ?></td>
                            <?php foreach($extendedFields as $name => $isSet): ?>
                                <?php if(isset($sr[$name])): ?>
                                    <td style="font-style: italic;"><?php echo htmlentities($sr[$name]); ?></td>
                                <?php else: ?>
                                    <td>&nbsp;</td>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </tr>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endforeach; ?>
<?php endif; ?>

<div id="hiddenElements">
    <div class="portalTableContainer"></div>
    <div class="headline"><h3>Test</h3></div>
    <div class="table_frame">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Tabelle</th>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Suchstring</th>
                    <th>Suchfeld</th>
                    <th>Zus&auml;tzliches Ergebnis</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <div class="table_row">
        <table>
            <tbody>
                <tr>
                    <td class="search_tablename"></td>
                    <td class="search_id"></td>
                    <td class="search_name"></td>
                    <td class="search_string"></td>
                    <td class="search_field"></td>
                    <td class="search_ext_field"></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
        
<div id="progessDialog" class="panel panel-default">
    <div class="panel-heading"><b>Systeme werden abgefragt ...</b><span class="glyphicon glyphicon-remove"></span></div>
    <div class="panel-body">
        <div class="progress progress-striped active">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"><span><nobr></nobr></span></div>
        </div>
        <div id="show_results_container">
            <button id="show_results" class="btn btn-default">Ergebnisse anzeigen</button>
        </div>
    </div>
</div>