<script type="text/javascript" src="<?php echo $this->mediaUrl; ?>sb_admin2/js/plugins/dataTables/jquery.dataTables.js"></script>
<script type="text/javascript" src="<?php echo $this->mediaUrl; ?>sb_admin2/js/plugins/dataTables/dataTables.bootstrap.js"></script>
    
<script>
    $(document).ready(function() {
        $('#pluginlist').dataTable({
            "sPaginationType": "full_numbers",
            "aoColumns": [null, null],
            "bStateSave": true
        });
    });

</script>

<h1>Plugins</h1>
<hr>
   
<div class="panel panel-default">
    <div class="panel-heading">
        <b>Installierte Plugins</b>
    </div>
    <div class="panel-body">
        <?php if (count($this->collection) > 0): ?>
            <table id="pluginlist" class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Anzahl gefundener Installationen</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->collection as $plugin): ?>
                        <tr>
                            <td><a style="display: block;" href="<?php echo \lw_page::getInstance()->getUrl(array("portalsPlugin" =>"LwPortalsPlugins", "cmd" => "showDetail", "id" => $plugin->getId())); ?>"><?php echo $plugin->getValueByKey("name"); ?></a></td>
                            <td><?php echo $plugin->getValueByKey("installs"); ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <p>keine Portale vorhanden</p>
        <?php endif; ?>
    </div>
</div>
