<h1>Konfiguration</h1>
<hr>    

<script>
    function isNumberKey(evt) {
        var charCode = (evt.which) ? evt.which : event.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57))
            return false;
        return true;
    }
</script>

<form id="md5check_form" class="form-horizontal" role="form" action="<?php echo \lw_page::getInstance()->getUrl(array("portalsPlugin" =>"LwPortalsConfig", "cmd" => "save")); ?>" method="POST">
    <div class="panel-body">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs">
            <li class="active"><a href="#ListtoolTab" data-toggle="tab" >Listtool</a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane fade in active" id="ListtoolTab">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <b>Parameter der Listtool-&Uuml;berwachung festlegen</b>
                    </div>
                    <div class="panel-body">
                        <div class="col-lg-6">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <b>Listen</b>
                                </div>
                                <div class="panel-body">
                                    <p style="text-align: justify">
                                        Wahrnungsmail verschicken, wenn sich die Anzahl der Listen um den angegebenen Schwellenwert verringert und
                                        die Zahl von angelegten Listen, die Mindestanzahl &uuml;bersteigt.                                        
                                    </p>
                                    <div class="form-group">
                                        <label for="list_warn_value" class="col-sm-7 control-label">Schwellenwert ( in % )</label>
                                        <div class="col-sm-3">
                                            <input id="list_warn_value" class="form-control" type="text" name="list_warn_value" value="<?php if(isset($this->portalsConfig["list_warn_value"])) { echo $this->portalsConfig["list_warn_value"]; } ?>" onkeypress="return isNumberKey(event)"/>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="list_min_value" class="col-sm-7 control-label">Mindestanzahl</label>
                                        <div class="col-sm-3">
                                            <input id="list_min_value" class="form-control" type="text" name="list_min_value" value="<?php if(isset($this->portalsConfig["list_min_value"])) { echo $this->portalsConfig["list_min_value"]; } ?>" onkeypress="return isNumberKey(event)"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <b>Gespeicherte Dateien</b>
                                </div>
                                <div class="panel-body">
                                    <p style="text-align: justify">
                                        Wahrnungsmail verschicken, wenn sich die Anzahl der Dateien um den angegebenen Schwellenwert verringert und
                                        die Zahl von gespeicherten Dateien, die Mindestanzahl &uuml;bersteigt.                                        
                                    </p>
                                    <div class="form-group">
                                        <label for="files_warn_value" class="col-sm-7 control-label">Schwellenwert ( in % )</label>
                                        <div class="col-sm-3">
                                            <input id="files_warn_value" class="form-control" type="text" name="files_warn_value" value="<?php if(isset($this->portalsConfig["files_warn_value"])) { echo $this->portalsConfig["files_warn_value"]; } ?>" onkeypress="return isNumberKey(event)"/>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="files_min_value" class="col-sm-7 control-label">Mindestanzahl</label>
                                        <div class="col-sm-3">
                                            <input id="files_min_value" class="form-control" type="text" name="files_min_value" value="<?php if(isset($this->portalsConfig["files_min_value"])) { echo $this->portalsConfig["files_min_value"]; } ?>" onkeypress="return isNumberKey(event)"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <b>Zu infomierende Personen</b>
                                </div>
                                <div class="panel-body">
                                    <div class="form-group">
                                        <label class="col-sm-1 control-label">1</label>
                                        <div class="col-sm-8">
                                            <input type="email" class="form-control" type="text" name="email[1]" value="<?php if(isset($this->portalsConfig["email"][1])) { echo $this->portalsConfig["email"][1]; } ?>"/>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-1 control-label">2</label>
                                        <div class="col-sm-8">
                                            <input type="email" class="form-control" type="text" name="email[2]" value="<?php if(isset($this->portalsConfig["email"][2])) { echo $this->portalsConfig["email"][2]; } ?>"/>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-1 control-label">3</label>
                                        <div class="col-sm-8">
                                            <input type="email" class="form-control" type="text" name="email[3]" value="<?php if(isset($this->portalsConfig["email"][3])) { echo $this->portalsConfig["email"][3]; } ?>"/>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-1 control-label">4</label>
                                        <div class="col-sm-8">
                                            <input type="email" class="form-control" type="text" name="email[4]" value="<?php if(isset($this->portalsConfig["email"][4])) { echo $this->portalsConfig["email"][4]; } ?>"/>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-1 control-label">5</label>
                                        <div class="col-sm-8">
                                            <input type="email" class="form-control" type="text" name="email[5]" value="<?php if(isset($this->portalsConfig["email"][5])) { echo $this->portalsConfig["email"][5]; } ?>"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>      
        </div>
    </div>   
    <div class="form-group">
        <div class="col-sm-offset-1 col-sm-10">
            <button type="submit" class="btn btn-primary">speichern</button>
        </div>
    </div>
</form>
