<script>
    $(document).ready(function() {       
        var nonHttpsResondingPortals = 0;
            
        $(window).bind("resize", function() {
            elementResize();
        });
        function elementResize() {
            $("#progessDialog").css("left", ( ($("#page-wrapper").width() / 2 ) - $("#progessDialog").width() / 2 ) );
            $("#progessDialog").css("top", ( ($("#page-wrapper").height() / 4 ) - $("#progessDialog").height() / 2 ) );
        }
        elementResize();

        function getPreparedArray()
        {
            var portalArray =  new Object();
            <?php

            if ($this->entity){
                echo "" . PHP_EOL;
                if($this->entity->getValueByKey("scan_exclude") < 1 ){
                    echo "portalArray['" . $this->entity->getValueByKey("name") . "'] = " . $this->entity->getId() . ";" . PHP_EOL;
                }
                echo "" . PHP_EOL;
            } else if($this->collection) {

                echo "" . PHP_EOL;
                foreach($this->collection as $portal){
                    if($portal->getValueByKey("scan_exclude") < 1 ){
                        echo "portalArray['" . $portal->getValueByKey("name") . "'] = " . $portal->getId() . ";" . PHP_EOL;
                    }
                }
                echo "" . PHP_EOL;
            }

            ?>
            return portalArray;
        }

      
       $("#submit_btn").click(function(){
            nonHttpsResondingPortals = 0;
           
            $("#container_tables").hide();
            $("#progessDialog #error_container").hide();
            $("#progessDialog div.progress-bar").removeClass("progress-bar-success");
            $("#progessDialog").removeClass("panel-success");
            $("#progessDialog div.progress-bar").removeClass("progress-bar-warning");
            $("#progessDialog").removeClass("panel-warning");
            $("#progessDialog").addClass("panel-default");
            $("#progessDialog div.panel-heading span").hide();
            $("#progessDialog #show_results_container").hide();
            $("#container_tables > table > tbody").html("");
            $("#progessDialog").show();                

            var portalArray = getPreparedArray();
            var portalsCount = <?php
                if($this->entity) {
                    echo 1;

                } else if($this->collection) {
                    $i = 0;
                    foreach($this->collection as $portal){
                        if($portal->getValueByKey("scan_exclude") < 1 ){
                            $i++;

                        }
                    } echo $i;
                }
                        ?>;
            var i = 0;
            var percent = 0;
            $.each(portalArray, function(portal, portal_id) {
                $.ajax({
                     url: "<?php echo \lw_page::getInstance()->getUrl(array("portalsPlugin" =>"LwPortalsHttpsCheck", "cmd" => "checkHttps", "ajax" => 1)); ?>&id=" + portal_id,
                     type: "POST",
                     dataType: "json",
                     processData: false,
                     contentType: false
                     }).done(function(response){
                         //alert(response);
                         i++;
                         percent = ((i/portalsCount) * 100).toFixed(2);
                         $("#progessDialog div.progress-bar").css("width", percent + "%");
                         $("#progessDialog div.progress-bar span").html("<nobr>" + portal +" ( " + percent +"% )</nobr>");
                         
                         buildTable(response);
                         
                         if( i === portalsCount) {
                            if(nonHttpsResondingPortals > 0) {
                                $("#progessDialog div.progress-bar").addClass("progress-bar-warning");
                                $("#progessDialog").addClass("panel-warning");
                                $("#progessDialog #error_container span#error_content").html("Mindestens ein Portal antwortet nicht auf eine HTTPS-Anfragen.");
                                $("#progessDialog #error_container").show();
                            } else {
                                $("#progessDialog div.progress-bar").addClass("progress-bar-success");
                                $("#progessDialog").addClass("panel-success");
                            }
                            $("#progessDialog").removeClass("panel-default");                            
                            $("#progessDialog div.panel-heading span").show();
                            $("#progessDialog #show_results_container").show();
                         }
                 });
            });
       });

       function buildTable(jsonResponse)
       {
           $.each(jsonResponse, function(portal, results) {
               $.each(results, function(nr, result) {
                   if( result.https !== undefined && result.https !== false ) {
                       var status = "<span style=\"color:green;\" class=\"glyphicon glyphicon-ok\"></span>";
                   } else {
                       var status = "<span style=\"color:darkred;\" class=\"glyphicon glyphicon-remove\"></span>";
                       nonHttpsResondingPortals++;
                   }
                   
                   $("#hiddenElements div.table_row tr td.portalName").html(portal);
                   $("#hiddenElements div.table_row tr td.connectionStatus").html(status);

                   $("#hiddenElements div.table_row tr").clone().appendTo($("#container_tables > table > tbody"));
               });

            });
       }

       $("#progessDialog div.panel-heading span").click(function(){
          $("#container_tables").show();
          $("#progessDialog").hide();
       });
       $("#progessDialog #show_results").click(function(){
          $("#container_tables").show();
          $("#progessDialog").hide();
       });       
       
    });
</script>
<style>
    #container_tables, #hiddenElements{display: none;}
    #progessDialog{
        position: absolute;
        top: 100px;
        left: 200px;
        width: 600px;
        display: none;        
    }
    #progessDialog div.panel-heading span{
        float: right;
        cursor: pointer;
        display: none;
    }

    .progress-bar span{
        font-weight: bold;
        text-shadow: #333 2px 2px 1px;
    }
    
    #progessDialog #error_container {
        display: none;
        margin-bottom: 10px;
    }
    
    #progessDialog #error_container #error_content{
        padding-left: 10px;
        color: darkred;
    }
    
    #show_results_container button{float: right;}
    #show_results_container{display: none;}
    
</style>
<?php if($this->entity): ?>
    <h1>HTTPSCheck - <?php echo $this->entity->getValueByKey("name"); ?></h1>
<?php else: ?>
    <h1>HTTPSCheck - Alle Portale</h1>
<?php endif; ?>
<hr>

<form id="md5check_form" class="form-horizontal" role="form" method="POST">
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input type="button" id="submit_btn" class="btn btn-default" value="HTTPS-Verbindungstest starten">
        </div>
    </div>
</form>

<div id="container_tables">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Portal</th>
                <th style="width: 135px;">Status ( HTTPS )</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>


<div id="hiddenElements">
    <div class="table_row">
        <table>
            <tbody>
                <tr>
                    <td class="portalName"></td>
                    <td class="connectionStatus"></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>


<div id="progessDialog" class="panel panel-default">
    <div class="panel-heading"><b>Systeme werden abgefragt ...</b><span class="glyphicon glyphicon-remove"></span></div>
    <div class="panel-body">
        <div class="progress progress-striped active">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"><span><nobr></nobr></span></div>
        </div>
        <div id="error_container">
            <span id="error_lable" class="label label-danger">Fehler</span><span id="error_content">asduhaisduhas</span>
        </div>
        <div id="show_results_container">
            <button id="show_results" class="btn btn-default">Ergebnisse anzeigen</button>
        </div>
    </div>
</div>            