<?php if(isset($this->pageIndexes)): ?>
    <script type="text/javascript" src="<?php echo $this->mediaUrl . "modules/spinloader/spin.min.js"; ?>"></script>

    <style>    
        #greyOverlay{
            display:none;
            position:absolute;
            top:0px;
            left:0px;
            bottom:0px;
            right:0px;
            width:100%;
            height:100%;
            z-index: 10;
            background-color: #fff;
            opacity: 0.7;
            filter: Alpha(Opacity=70);
        }
    </style>
<?php endif; ?>
<?php if($this->entity): ?>
    <h1>Md5 - <?php echo $this->entity->getValueByKey("name"); ?></h1>
<?php else: ?>
    <h1>Md5 - Alle Portale</h1>
<?php endif; ?>
<hr>   

<?php if($this->entity): ?>
    <?php if(isset($this->pageIndexes["portals"])) { $indexPortals = $this->pageIndexes["portals"]; } else { $indexPortals = 0; } ?>
    <a href="<?php echo \lw_page::getInstance($indexPortals)->getUrl(array("portalsPlugin" =>"LwPortalsList", "cmd" => "showDetail", "id" => $this->entity->getId())); ?>" title="zur&uuml;ck"><span class="glyphicon glyphicon-arrow-left"></span></a>
<?php endif; ?>    
<?php if(isset($this->pageIndexes)): ?>
    <div id="greyOverlay">&nbsp;</div> 
<?php endif; ?>
<form id="md5check_form" class="form-horizontal" role="form" action="<?php echo $this->actionUrl; ?>" method="POST" ENCTYPE="multipart/form-data">

    <div class="form-group">
        <label class="col-sm-2 control-label">Datei Pfad</label>
        <div class="col-sm-4">
            <select id="configPath" name="configPath" class="form-control">
                <?php foreach ($this->paths as $key => $value): ?>
                    <option value="CONFIG:path_<?php echo $key; ?>" <?php if($this->post["configPath"] == $key): ?>selected="selected"<?php endif; ?>><?php echo $key; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="col-sm-6">
            <input id="filePath" class="form-control" type="text" name="path" value="<?php echo $this->post["path"]; ?>"/>
        </div>
    </div>
    
    <div class="form-group">
        <label for="expectedMd5" class="col-sm-2 control-label">Md5 ( erwartet )</label>
        <div class="col-sm-10">
            <input id="expectedMd5" class="form-control" type="text" name="expectedMd5" value="<?php echo $this->post["expectedMd5"]; ?>"/>
        </div>
    </div>

    <div class="form-group">
        <label for="inputFile" class="col-sm-2 control-label">CSV Upload</label>
        <div class="col-sm-10">
            <input id="inputFile" name="inputFile" type="file">
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default" onclick="
                            $('#greyOverlay').show();
                            var opts = {
                                lines: 13, // The number of lines to draw
                                length: 16, // The length of each line
                                width: 14, // The line thickness
                                radius: 25, // The radius of the inner circle
                                corners: 1, // Corner roundness (0..1)
                                rotate: 0, // The rotation offset
                                color: '#2A649D', // #rgb or #rrggbb
                                speed: 1, // Rounds per second
                                trail: 44, // Afterglow percentage
                                shadow: true, // Whether to render a shadow
                                hwaccel: false, // Whether to use hardware acceleration
                                className: 'spinner', // The CSS class to assign to the spinner
                                zIndex: 2e9, // The z-index (defaults to 2000000000)
                                top: '350', // Top position relative to parent in px
                                left: 'auto' // Left position relative to parent in px
                            };
                            var target = document.getElementById('greyOverlay');
                            var spinner = new Spinner(opts).spin(target);">pr&uuml;fen</button>
        </div>
    </div>
</form>
    
<?php if($this->results): ?>    
    <?php if($this->entity): ?>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Pfad</th>
                    <th>Erwarteter Md5-Wert</th>
                    <th>Server Md5-Wert</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->results[$this->entity->getValueByKey("name")] as $file): ?>
                    <tr style="color: <?php if($file["expectedMd5"] == $file["recievedMd5"] && $file["expectedMd5"] != ""): ?>green<?php else: ?>darkred<?php endif; ?>">
                        <td><?php echo $file["completePath"]; ?></td>
                        <td><?php echo $file["expectedMd5"]; ?></td>
                        <td><?php if(!$file["recievedMd5"]){ echo "Datei existiert nicht !"; } else { echo $file["recievedMd5"]; } ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <?php foreach($this->results as $portal => $files): ?>
            <h3><?php echo $portal; ?></h3>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Pfad</th>
                        <th>Erwarteter Md5-Wert</th>
                        <th>Server Md5-Wert</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($files as $file): ?>
                        <tr style="color: <?php if($file["expectedMd5"] == $file["recievedMd5"] && $file["expectedMd5"] != ""): ?>green<?php else: ?>darkred<?php endif; ?>">
                            <td><?php echo $file["completePath"]; ?></td>
                            <td><?php echo $file["expectedMd5"]; ?></td>
                            <td><?php if(!$file["recievedMd5"]){ echo "Datei existiert nicht !"; } else { echo $file["recievedMd5"]; } ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endif; ?>