<script>
    $(document).ready(function() {  
        $(window).bind("resize", function() {
            elementResize();
        });
        function elementResize() {
            $("#progessDialog").css("left", ( ($("#page-wrapper").width() / 2 ) - $("#progessDialog").width() / 2 ) );
            $("#progessDialog").css("top", ( ($("#page-wrapper").height() / 4 ) - $("#progessDialog").height() / 2 ) );
        }
        elementResize();
        
        function getPreparedArray()
        {
            var portalArray =  new Object();
            <?php
            
            if ($this->entity){
                echo "" . PHP_EOL;
                echo "portalArray['" . $this->entity->getValueByKey("name") . "'] = " . $this->entity->getId() . ";" . PHP_EOL;
                echo "" . PHP_EOL;
            } else if($this->collection) {
                
                echo "" . PHP_EOL;
                foreach($this->collection as $portal){
                    echo "portalArray['" . $portal->getValueByKey("name") . "'] = " . $portal->getId() . ";" . PHP_EOL;
                }
                echo "" . PHP_EOL;
            }
            
            ?>
            return portalArray;
        }
        
       var data = new FormData();
       $("#inputFile").change(function(){
            data.append('inputFile', this.files[0]);
       });

       $("#submit_btn").click(function(){
            if($("#inputFile").val() !== "" || ($("#filePath").val() !== "" && $("#expectedMd5").val() !== "")){
                $("#container_tables").hide();    
                $("#container_tables").html("");    
                $("#progessDialog").show();    
                
                if($("#inputFile").val() === ""){
                    data.append('configPath', $("#configPath").val());
                    data.append('path', $("#filePath").val());
                    data.append('expectedMd5', $("#expectedMd5").val());

                }   

                var portalArray = getPreparedArray();
                var portalsCount = <?php if($this->entity) { echo 1; } else if($this->collection) { echo count($this->collection); } ?>;
                var i = 0;
                var percent = 0;
                $.each(portalArray, function(portal, portal_id) {
                    $.ajax({
                         url: "<?php echo \lw_page::getInstance()->getUrl(array("portalsPlugin" =>"LwPortalsMd5", "cmd" => "checkMd5", "ajax" => 1)); ?>&id=" + portal_id,
                         data: data,
                         type: "POST",
                         dataType: "json",
                         processData: false,
                         contentType: false
                         }).done(function(response){
                         //successful
                         //alert(response);
                         buildTable(response);
                     });
                     i++;
                     percent = ((i/portalsCount) * 100).toFixed(2);
                     $("#progessDialog div.progress-bar").css("width", percent + "%");
                     $("#progessDialog div.progress-bar span").html("<nobr>" + portal +" ( " + percent +"% )</nobr>");
                });
                
                $("#progessDialog div.panel-heading span").show();    
                $("#progessDialog #show_results_container").show();    
            }
       });
       
       function buildTable(jsonResponse)
       {                      
           $.each(jsonResponse, function(portal, results) {
               $("#hiddenElements div.portalTableContainer").attr("id","container_" + portal).clone().appendTo($("#container_tables"));
               $("#hiddenElements div.headline h3").html(portal).clone().appendTo($("#container_tables div#container_" + portal));
               $("#hiddenElements div.table_frame table").clone().appendTo($("#container_tables div#container_" + portal));
               $.each(results, function(nr, result) {
                   $("#hiddenElements div.table_row tr td.completePath").html(result.completePath);
                   $("#hiddenElements div.table_row tr td.expectedMd5").html(result.expectedMd5);
                   
                   if(result.recievedMd5 === false) {
                       $("#hiddenElements div.table_row tr td.recievedMd5").html("Datei existiert nicht!");
                   } else {
                       $("#hiddenElements div.table_row tr td.recievedMd5").html(result.recievedMd5);
                   }
                   
                   if(result.recievedMd5 === result.expectedMd5) {
                       $("#hiddenElements div.table_row tr").css("color","green");
                   } else {
                      $("#hiddenElements div.table_row tr").css("color","darkred");
                   }
                   
                   $("#hiddenElements div.table_row tr").clone().appendTo($("#container_tables div#container_" + portal + " > table > tbody"));
               });
               
            });
       }
       
       $("#progessDialog div.panel-heading span").click(function(){
          $("#container_tables").show(); 
          $("#progessDialog").hide();
       });
       $("#progessDialog #show_results").click(function(){
          $("#container_tables").show(); 
          $("#progessDialog").hide();
       });
        
    });
</script>
<style>
    #container_tables, #hiddenElements{display: none;}
    #progessDialog{
        position: absolute;
        top: 100px;
        left: 200px;
        width: 600px;
        display: none;
    }
    #progessDialog div.panel-heading span{
        float: right;
        cursor: pointer;
        display: none;
    }
    
    .progress-bar span{
        font-weight: bold;
        text-shadow: #333 2px 2px 1px;
    }
    
    #show_results_container button{float: right;}
    #show_results_container{display: none;}
</style>   
    
<?php if($this->entity): ?>
    <h1>Md5 - <?php echo $this->entity->getValueByKey("name"); ?></h1>
<?php else: ?>
    <h1>Md5 - Alle Portale</h1>
<?php endif; ?>
<hr>   

<?php if($this->entity): ?>
    <?php if(isset($this->pageIndexes["portals"])) { $indexPortals = $this->pageIndexes["portals"]; } else { $indexPortals = 0; } ?>
    <a href="<?php echo \lw_page::getInstance($indexPortals)->getUrl(array("portalsPlugin" =>"LwPortalsList", "cmd" => "showDetail", "id" => $this->entity->getId())); ?>" title="zur&uuml;ck"><span class="glyphicon glyphicon-arrow-left"></span></a>
<?php endif; ?>    

<form id="md5check_form" class="form-horizontal" role="form" method="POST" ENCTYPE="multipart/form-data">

    <div class="form-group">
        <label class="col-sm-2 control-label">Datei Pfad</label>
        <div class="col-sm-4">
            <select id="configPath" name="configPath" class="form-control">
                <?php foreach ($this->paths as $key => $value): ?>
                    <option value="CONFIG:path_<?php echo $key; ?>" <?php if($this->post["configPath"] == $key): ?>selected="selected"<?php endif; ?>><?php echo $key; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="col-sm-6">
            <input id="filePath" class="form-control" type="text" name="path" value="<?php echo $this->post["path"]; ?>"/>
        </div>
    </div>
    
    <div class="form-group">
        <label for="expectedMd5" class="col-sm-2 control-label">Md5 ( erwartet )</label>
        <div class="col-sm-10">
            <input id="expectedMd5" class="form-control" type="text" name="expectedMd5" value="<?php echo $this->post["expectedMd5"]; ?>"/>
        </div>
    </div>

    <div class="form-group">
        <label for="inputFile" class="col-sm-2 control-label">CSV Upload</label>
        <div class="col-sm-10">
            <input id="inputFile" name="inputFile" type="file">
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input type="button" id="submit_btn" class="btn btn-default" value="pr&uuml;fen">
        </div>
    </div>
</form>
    
<div id="container_tables"></div>    
    
<?php if($this->results): ?>    
    <?php if($this->entity): ?>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Pfad</th>
                    <th>Erwarteter Md5-Wert</th>
                    <th>Server Md5-Wert</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->results[$this->entity->getValueByKey("name")] as $file): ?>
                    <tr style="color: <?php if($file["expectedMd5"] == $file["recievedMd5"] && $file["expectedMd5"] != ""): ?>green<?php else: ?>darkred<?php endif; ?>">
                        <td><?php echo $file["completePath"]; ?></td>
                        <td><?php echo $file["expectedMd5"]; ?></td>
                        <td><?php if(!$file["recievedMd5"]){ echo "Datei existiert nicht !"; } else { echo $file["recievedMd5"]; } ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <?php foreach($this->results as $portal => $files): ?>
            <h3><?php echo $portal; ?></h3>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Pfad</th>
                        <th>Erwarteter Md5-Wert</th>
                        <th>Server Md5-Wert</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($files as $file): ?>
                        <tr style="color: <?php if($file["expectedMd5"] == $file["recievedMd5"] && $file["expectedMd5"] != ""): ?>green<?php else: ?>darkred<?php endif; ?>">
                            <td><?php echo $file["completePath"]; ?></td>
                            <td><?php echo $file["expectedMd5"]; ?></td>
                            <td><?php if(!$file["recievedMd5"]){ echo "Datei existiert nicht !"; } else { echo $file["recievedMd5"]; } ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endif; ?>

<div id="hiddenElements">
    <div class="portalTableContainer"></div>
    <div class="headline"><h3>Test</h3></div>
    <div class="table_frame">        
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Pfad</th>
                    <th>Erwarteter Md5-Wert</th>
                    <th>Server Md5-Wert</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <div class="table_row">
        <table>
            <tbody>
                <tr>
                    <td class="completePath"></td>
                    <td class="expectedMd5"></td>
                    <td class="recievedMd5"></td>
                </tr>            
            </tbody>
        </table>
    </div>
</div>      
            
            
<div id="progessDialog" class="panel panel-info">
    <div class="panel-heading"><b>Systeme werden abgefragt ...</b><span class="glyphicon glyphicon-remove"></span></div>
    <div class="panel-body">
        <div class="progress progress-striped active">
            <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"><span><nobr></nobr></span></div>
        </div>
        <div id="show_results_container">
            <button id="show_results" class="btn btn-default">Ergebnisse anzeigen</button>
        </div>
    </div>
</div>